declare -A dots=(
  [./dots/tmux]="$HOME/.config/tmux"
  [./dots/kitty]="$HOME/.config/kitty"
  [./dots/ghostty]="$HOME/.config/ghostty"
  [./dots/gtk-3.0]="$HOME/.config/gtk-3.0"
  [./dots/gtk-4.0]="$HOME/.config/gtk-4.0"
  [./dots/hypr]="$HOME/.config/hypr"
  [./dots/nvim]="$HOME/.config/nvim"
  [./dots/starship]="$HOME/.config/starship"
  [./dots/uwsm]="$HOME/.config/uwsm"
  [./dots/zed]="$HOME/.config/zed"
  [./dots/.zprofile]="$HOME/.zprofile"
  [./dots/.zshrc]="$HOME/.zshrc"
  [./dots/proton/vpn.json]="$HOME/.config/Proton/VPN/settings.json"
)
