install=(paru -S --needed)

pkgs=(
  ninja
  meson
  cmake
  xmake
  mold
  gcc
  clang
  zsh
  neovim
  kitty
  tmux
  starship
  docker-desktop
  nautilus
  mission-center
  gnome-font-viewer
  gnome-calculator
  proton-vpn-gtk-app
  vesktop-bin
  uwsm
  adw-gtk-theme
  app2unit-git
  awww-git
  ttf-material-symbols-variable-git
  ttf-comic-mono-git
  noto-fonts-jp-vf
  noto-fonts-emoji
  fcitx5-im
  mozc-ut
  fcitx5-mozc-ut
  rtk-bin
  lazygit
)
