install=(paru -S --needed --noconfirm)

pkgs=(
  ninja
  meson
  cmake
  xmake
  gcc
  clang
  zed
  neovim
  ghostty
  docker-desktop
  visual-studio-code-bin
  nautilus
  blueberry
  zen-browser
  spotify-edge
  mission-center
  gnome-font-viewer
  gnome-calculator
  totem
  vesktop
  uwsm
  app2unit-git
  awww-git
)
