install=(paru -S --needed)

pkgs=(
  ninja
  meson
  cmake
  xmake
  gcc
  clang
  zed
  zsh
  neovim
  ghostty
  kitty
  tmux
  starship
  docker-desktop
  visual-studio-code-bin
  nautilus
  blueberry
  zen-browser
  spotify-edge
  mission-center
  gnome-font-viewer
  gnome-calculator
  proton-vpn-gtk-app
  totem
  vesktop
  uwsm
  adw-gtk-theme
  app2unit-git
  awww-git
  ttf-material-symbols-variable-git
  ttf-comic-mono-git
  noto-fonts-cjk
  noto-fonts-emoji
  fcitx5-im
  fcitx5-mozc
)
