#!/bin/sh

source ${PALLETS_DIR}/dark_pallet.sh
source ${PALLETS_DIR}/get_accent_color.sh

readonly BAR_BACK_COLOR=${ALPHA_100}${BG_1}
readonly BAR_BORDER_COLOR=${ALPHA_100}${BG_0}
readonly LABEL_NORMAL_COLOR=${ALPHA_100}${FG_1}
readonly LABEL_HIGHLIGHT_COLOR=${ALPHA_100}${BG_0}
readonly ICON_NORMAL_COLOR=${ALPHA_100}${FG_1}
readonly ICON_HIGHLIGHT_COLOR=${ALPHA_100}${BG_0}
readonly SPACE_ACTIVE_BACK_COLOR=${ALPHA_100}${ACCENT_COLOR}
readonly SPACE_ACTIVE_ICON_COLOR=${ALPHA_100}${FG_1}
readonly SPACE_INACTIVE_ICON_COLOR=${ALPHA_100}${FG_4}
readonly SPACE_BRACKET_BACK_COLOR=${ALPHA_100}${BG_2}
readonly SPACE_BRACKET_BORDER_COLOR=${ALPHA_100}${BG_3}
readonly APPBAR_BRACKET_BACK_COLOR=${ALPHA_100}${BG_2}
readonly APPBAR_BRACKET_BORDER_COLOR=${ALPHA_100}${BG_3}
readonly POPUP_BACK_COLOR=${ALPHA_100}${BG_1}
readonly POPUP_BORDER_COLOR=${ALPHA_100}${BG_0}
readonly BREW_BRACKET_BACK_COLOR=${ALPHA_100}${BG_2}
readonly BREW_BRACKET_BORDER_COLOR=${ALPHA_100}${BG_3}
readonly BREW_ERROR_COLOR=${ALPHA_100}${RED}
