[ags]
src = "ags"
dest = ".config/ags"

[hypr]
src = "hypr"
dest = ".config/hypr"

[nvim]
src = "nvim"
dest = ".config/nvim"

[sheldon]
src = "sheldon"
dest = ".config/sheldon"

[zshrc]
src = ".zshrc"
dest = ""