[ttf-roboto]
type = "font"
name = "Roboto"
install = "ttf-roboto"
manager = "paru"

[material-symbol]
type = "font"
name = "MaterialSymbolsSharp"
install = "material-symbols-git"
manager = "paru"

[bun]
type = "tool"
name = "bun"
install = "bun-bin"
manager = "paru"

[ags]
type = "tool"
name = "ags"
install = 'ags'
manager = "paru"

[matugen]
type = "tool"
name = "matugen"
install = "matugen-bin"
manager = "paru"

[neovim]
type = "tool"
name = "nvim"
install = "neovim"
manager = "paru"

[swww]
type = "tool"
name = "swww"
install = "swww-git"
manager = "paru"