[zsh]
name = "zsh"
manager = "paru"
command = "chsh -s /bin/zsh"

[hyprshot]
name = "hyprshot"
manager = "paru"

[hyprpicker]
name = "hyprpicker"
manager = "paru"

[ttf-google-sans]
name = "ttf-google-sans"
manager = "paru"

[ttf-roboto]
name = "ttf-roboto"
manager = "paru"

[ttf-roboto-flex]
name = "ttf-roboto-flex"
manager = "paru"

[noto-fonts-cjk-vf]
name = "noto-fonts-cjk-vf"
manager = "paru"

[note-fonts-emoji]
name = "noto-fonts-emoji"
manager = "paru"

[material-symbol]
name = "ttf-material-symbols-variable"
manager = "paru"

[bun]
name = "bun-bin"
manager = "paru"

[ags]
name = 'aylurs-gtk-shell'
manager = "paru"

[matugen]
name = "matugen-bin"
manager = "paru"

[neovim]
name = "neovim"
manager = "paru"

[swww]
name = "swww"
manager = "paru"