[ttf-roboto]
name = "ttf-roboto"
manager = "paru"

[ttf-roboto-flex]
name = "ttf-roboto-flex"
manager = "paru"

[material-symbol]
name = "ttf-material-symbols-variable"
manager = "paru"

[bun]
name = "bun-bin"
manager = "paru"

[ags]
name = 'aylurs-gtk-shell'
manager = "paru"

[matugen]
name = "matugen-bin"
manager = "paru"

[neovim]
name = "neovim"
manager = "paru"

[swww]
name = "swww"
manager = "paru"