[ttf-roboto]
name = "ttf-roboto"
manager = "paru"

[material-symbol]
name = "ttf-material-symbols-variable"
manager = "paru"

[bun]
name = "bun-bin"
manager = "paru"

[ags]
name = 'ags'
manager = "paru"

[matugen]
name = "matugen-bin"
manager = "paru"

[neovim]
name = "neovim"
manager = "paru"

[swww]
name = "swww"
manager = "paru"

[libastal]
name = "libastal-git"
manager = "paru"

[lua-libastal]
name = "lua-libastal-git"
manager = "paru"

[lua-lgi]
name = "lua-lgi-git"
manager = "paru"

[lua]
name = "lua"
manager = "paru"