[symlinks]
".zprofile" = "/home/hato/.zprofile"
".zshrc" = "/home/hato/.zshrc"
"ghostty/config" = "/home/hato/.config/ghostty/config"
"gtk-3.0/bookmarks" = "/home/hato/.config/gtk-3.0/bookmarks"
"gtk-3.0/gtk.css" = "/home/hato/.config/gtk-3.0/gtk.css"
"gtk-3.0/settings.ini" = "/home/hato/.config/gtk-3.0/settings.ini"
"gtk-4.0/gtk.css" = "/home/hato/.config/gtk-4.0/gtk.css"
"gtk-4.0/settings.ini" = "/home/hato/.config/gtk-4.0/settings.ini"
"hypr/hyprland.conf" = "/home/hato/.config/hypr/hyprland.conf"
"nvim/.claude/settings.local.json" = "/home/hato/.config/nvim/.claude/settings.local.json"
"nvim/init.lua" = "/home/hato/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/home/hato/.config/nvim/lazy-lock.json"
"nvim/lua/configs/keymap.lua" = "/home/hato/.config/nvim/lua/configs/keymap.lua"
"nvim/lua/configs/lazy.lua" = "/home/hato/.config/nvim/lua/configs/lazy.lua"
"nvim/lua/configs/options.lua" = "/home/hato/.config/nvim/lua/configs/options.lua"
"nvim/lua/init.lua" = "/home/hato/.config/nvim/lua/init.lua"
"nvim/lua/plugins/editor.lua" = "/home/hato/.config/nvim/lua/plugins/editor.lua"
"nvim/lua/plugins/lsp.lua" = "/home/hato/.config/nvim/lua/plugins/lsp.lua"
"nvim/lua/plugins/ui.lua" = "/home/hato/.config/nvim/lua/plugins/ui.lua"
"uwsm/default-id" = "/home/hato/.config/uwsm/default-id"
"uwsm/env" = "/home/hato/.config/uwsm/env"
"uwsm/env-hyprland" = "/home/hato/.config/uwsm/env-hyprland"
"zed/keymap.json" = "/home/hato/.config/zed/keymap.json"
"zed/settings.json" = "/home/hato/.config/zed/settings.json"
"zed/themes/github_pitch_theme.json" = "/home/hato/.config/zed/themes/github_pitch_theme.json"

[templates]
