[zed.files]
"zed" = "~/.config/zed"

[nvim.files]
"nvim" = "~/.config/nvim"

[hypr.files]
"hypr" = "~/.config/hypr"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[uwsm.files]
"uwsm" = "~/.config/uwsm"

[starship.files]
"starship" = "~/.config/starship"

[zsh.files]
".zshrc" = "~/.zshrc"
".zprofile" = "~/.zprofile"

[gtk3.files]
"gtk-3.0" = "~/.config/gtk-3.0"

[gtk4.files]
"gtk-4.0" = "~/.config/gtk-4.0"

